[package]
name = "kc_os"
version = "0.1.0"
edition = "2021"


[dependencies]
bootloader_api = { version = "0.11" }
volatile = "0.2.6"
spin = "0.9"
x86_64 = "0.14.11"

[build-dependencies]
bootimage = "0.10.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
